### ISSUE TITLE
Option to hide resize handlers, but allow resize when cursor is on an edge of the element

### ISSUE THREAD

**Issue by nikolay-borzov** [mauricius/vue-draggable-resizable#40]
Something like [this](https://dnd-grid.duton.lu/), but with the ability to resize in any direction

**Comment by mauricius** [comment]
Actually I think that it is possible to simulate this functionality with the current component, using a specific set of CSS rules. The only problem is that you need to override the `display` property, because the handles are displayed only when the component is active.

**Comment by nikolay-borzov** [comment]
Right, it is possible to achieve with CSS. It would be great to have this as a feature though.

**Comment by TitanFighter** [comment]
@nikolay-borzov If you implemented it, can you share CSS please?
Thanks in advance.

**Comment by nikolay-borzov** [comment]
Unfortunately I didn't

**Comment by mauricius** [comment]
@TitanFighter If you don't despise the `!important` declaration, you can use something like this (or just use selectors with higher specificity):

```css
.handle {
  background-color: transparent !important;
  border-width: 0px !important;
}
.handle.handle-tm {
  width: 100% !important;
  left: 5px !important;
}
.handle.handle-bm {
  width: 100% !important;
  left: 5px !important;
}
.handle.handle-mr {
  height: 100% !important;
  top: 5px !important;
}
.handle.handle-ml {
  height: 100% !important;
  top: 5px !important;
}
```
